apiVersion: v1
kind: Service
metadata:
  name: sms-service
spec:
  type: LoadBalancer
  selector:
    app: sms
  ports:
    - port: 80         # public port (user-facing)
      targetPort: 8000 # Django internal port

