apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
        - name: sms
          image: sohail28/sms:latest   # change to your actual image name
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: sms-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: sms-config
                  key: ALLOWED_HOSTS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn SMS.wsgi:application --bind 0.0.0.0:8000

