apiVersion: v1
kind: Secret
metadata:
  name: sms-secret
type: Opaque
data:
  DB_NAME: c21tcw==          # base64 for "smsdb"
  DB_USER: c21zdXNlcg==      # base64 for "smsuser"
  DB_PASSWORD: c21zcGFzcw==  # base64 for "smspass"

